// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// Start of fibonacci array with 1 and 2
var fibs = [1,2];
// Start our sum of even fibonacci numbers with 2
sum_of_even_fibs = 2;
// Starting at 3, go through each fibonacci number...
// (After every iteration, i will become the sum of the last two numbers in the array)
for (i = 3; i < 4000000; i = fibs[fibs.length - 1] + fibs[fibs.length - 2]) {
	// Add number to fibonacci array
  fibs[fibs.length] = i;
  // If the number is even...
  if (i % 2 === 0) {
		// Add it to our running sum
    sum_of_even_fibs += i;
  }
}
// Print out sum of even fibonacci numbers for verification
console.log(sum_of_even_fibs); // => 4,613,732